submetering <- data %>% select(Date_time, Sub_metering_1,Sub_metering_2,Sub_metering_3)
submetering$Date_time <- as.character(submetering$Date_time)
submetering_long <- gather(submetering, key = "Date_time")
submetering_long$Date_time <- strptime(submetering_long$Date_time, format = "%Y-%m-%d %H:%M:%S")
png(file = "plot3.png")
with(data, plot(Date_time,Sub_metering_1, type = "l",ylab = "Energy sub metering"))
with(data, lines(Date_time,Sub_metering_2, type = "l",col ="red", ylab = "Energy sub metering"))
with(data, lines(Date_time,Sub_metering_3, type = "l",col ="blue", ylab = "Energy sub metering"))
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), 
       col=c("black","red","blue"), pch ="-")
dev.off()
